name: CI Pipeline with SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Apply migrations
      run: python3 manage.py migrate

    - name: Run Bandit SAST
      run: bandit -r .

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.3.0
      with:
        projectBaseDir: ./
        args: >
          -Dsonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONARQUBE_ORG }}
